import type { HexBiome } from '@/types/biome';

/**
 * Kanonischer Katalog aller Hex-Biome. IDs müssen stabil bleiben.
 */
export const BIOMES: Record<string, HexBiome> = {
  aether_nebula: {
    id: 'aether_nebula',
    name: 'Äthernebel',
    blurb: 'Schimmernde Gasfelder voller Ätherpartikel.',
    tags: ['nebula', 'aether', 'research'],
    baseYield: { aether: 3, research: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 3 },
    hazards: { storm: 2, radiation: 1 },
    build: { allowed: ['aether_collector', 'resonance_tower'] },
    adjacency: { prefers: ['aether_well', 'crystal_reef'], avoids: ['trade_lane'] },
    palette: { base: '#3b2a6d', edge: '#5f4aa8', accent: '#8ad1ff' },
    decals: ['wisps', 'glow_arcs'],
  },
  aether_storm: {
    id: 'aether_storm',
    name: 'Äthersturmfeld',
    blurb: 'Elektrisch aufgeladene, chaotische Ätherfront.',
    tags: ['nebula', 'storm', 'hazard'],
    baseYield: { aether: 2 },
    moveCost: { airship: 3, frigate: 4, dreadnought: 5 },
    hazards: { storm: 3, gravity: 1 },
    build: { allowed: ['storm_anchor'] },
    adjacency: { prefers: ['aether_nebula'], avoids: ['trade_lane', 'skyfarms'] },
    palette: { base: '#2b213f', edge: '#8c3b1a', accent: '#f2b35b' },
    decals: ['lightning', 'torn_clouds'],
  },
  debris_field: {
    id: 'debris_field',
    name: 'Trümmersfeld',
    blurb: 'Wracks und Schrottgürtel mit wertvollem Metall.',
    tags: ['debris', 'salvage', 'industry'],
    baseYield: { ore: 2, coal: 1, luxury: 1 },
    moveCost: { airship: 2, frigate: 3, dreadnought: 3 },
    hazards: { corrosion: 2, piracy: 1 },
    build: { allowed: ['scrap_yard', 'recycler'] },
    adjacency: { prefers: ['pirate_haven', 'war_graveyard'], avoids: ['trade_lane'] },
    palette: { base: '#3a3a3a', edge: '#5b4e3b', accent: '#caa56b' },
    decals: ['wrecks', 'girders'],
  },
  asteroid_belt: {
    id: 'asteroid_belt',
    name: 'Asteroidengürtel',
    blurb: 'Reiche Erzadern und Bohrplattformen.',
    tags: ['mining', 'rocks'],
    baseYield: { ore: 3, fuel: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 3 },
    hazards: { gravity: 1 },
    build: { allowed: ['drill_consortium', 'blast_depot'] },
    adjacency: { prefers: ['gas_giant_rings', 'soot_cloud'] },
    palette: { base: '#2f2b28', edge: '#4a3f38', accent: '#b07f4f' },
    decals: ['boulders', 'rigs'],
  },
  soot_cloud: {
    id: 'soot_cloud',
    name: 'Industrie-Rauchwolke',
    blurb: 'Schwarzer Smog aus Dampfwerken und Hochöfen.',
    tags: ['industry', 'smog'],
    baseYield: { coal: 3, ore: 1, influence: 1 },
    moveCost: { airship: 2, frigate: 3, dreadnought: 3 },
    hazards: { corrosion: 2, heat: 1 },
    build: { allowed: ['foundry', 'steam_plant', 'customs'] },
    adjacency: { prefers: ['brass_metropolis', 'trade_lane'], avoids: ['skyfarms', 'crystal_reef'] },
    palette: { base: '#2a2a2a', edge: '#553c2a', accent: '#d58c28' },
    decals: ['smoke', 'stacks'],
  },
  brass_metropolis: {
    id: 'brass_metropolis',
    name: 'Messing-Metropole',
    blurb: 'Orbitale Ringstadt, Knoten globaler Einflüsse.',
    tags: ['urban', 'hub', 'trade'],
    baseYield: { influence: 3, luxury: 2, food: 1 },
    moveCost: { airship: 1, frigate: 1, dreadnought: 2 },
    hazards: { piracy: 1 },
    build: { allowed: ['guild_hall', 'embassy', 'police_dock', 'stock_exchange'] },
    adjacency: { prefers: ['trade_lane', 'skyfarms', 'soot_cloud'], avoids: ['aether_storm'] },
    palette: { base: '#6f5a2e', edge: '#402e14', accent: '#f2d070' },
    decals: ['ring_city', 'dirigibles'],
  },
  trade_lane: {
    id: 'trade_lane',
    name: 'Handelsroute',
    blurb: 'Schneller, gesicherter Konvoikorridor.',
    tags: ['trade', 'route'],
    baseYield: { luxury: 2, influence: 1, fuel: 1 },
    moveCost: { airship: 1, frigate: 1, dreadnought: 1 },
    hazards: { piracy: 2 },
    build: { allowed: ['toll_gate', 'relay', 'market'] },
    adjacency: { prefers: ['brass_metropolis', 'skyfarms'], avoids: ['pirate_haven'] },
    palette: { base: '#324a56', edge: '#1f2e36', accent: '#9fd3e6' },
    decals: ['beacons', 'lanes'],
  },
  pirate_haven: {
    id: 'pirate_haven',
    name: 'Piratennest',
    blurb: 'Getarnte Docks, Unterwelt und Beuteumschlag.',
    tags: ['piracy', 'black_market'],
    baseYield: { luxury: 2, influence: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 2 },
    hazards: { piracy: 3 },
    build: { allowed: ['black_market', 'scrambler'], banned: ['police_dock'] },
    adjacency: { prefers: ['debris_field', 'war_graveyard'], avoids: ['brass_metropolis', 'trade_lane'] },
    palette: { base: '#2a3135', edge: '#1b2023', accent: '#c94c4c' },
    decals: ['skull_flag', 'hidden_dock'],
  },
  war_graveyard: {
    id: 'war_graveyard',
    name: 'Kriegsfriedhof',
    blurb: 'Schlachtfeldrelikte und Schweigen.',
    tags: ['war_remnant', 'debris'],
    baseYield: { ore: 2, research: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 3 },
    hazards: { radiation: 2, anomaly: 1 },
    build: { allowed: ['memorial', 'salvage_pit'] },
    adjacency: { prefers: ['debris_field', 'relic_vault'], avoids: ['skyfarms'] },
    palette: { base: '#3b2f35', edge: '#231b1f', accent: '#9b7f8a' },
    decals: ['hulks', 'broken_cannon'],
  },
  relic_vault: {
    id: 'relic_vault',
    name: 'Relikt-Archiv',
    blurb: 'Uralte Uhrwerksstrukturen, verschlossene Kammern.',
    tags: ['ancient', 'research'],
    baseYield: { research: 3, luxury: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 2 },
    hazards: { anomaly: 2 },
    build: { allowed: ['observatory', 'archive'] },
    adjacency: { prefers: ['crystal_reef', 'war_graveyard'], avoids: ['soot_cloud'] },
    palette: { base: '#4a3b2f', edge: '#2b221a', accent: '#b69b7a' },
    decals: ['glyphs', 'armillary'],
  },
  crystal_reef: {
    id: 'crystal_reef',
    name: 'Kristallriff',
    blurb: 'Leuchtende Ätherkristalle in schwebenden Riffen.',
    tags: ['crystal', 'aether', 'research'],
    baseYield: { aether: 2, research: 2 },
    moveCost: { airship: 2, frigate: 3, dreadnought: 3 },
    hazards: { anomaly: 2 },
    build: { allowed: ['harmonics_chamber', 'crystal_saw'] },
    adjacency: { prefers: ['aether_well', 'aether_nebula'], avoids: ['soot_cloud'] },
    palette: { base: '#264b4f', edge: '#163235', accent: '#7fe0d6' },
    decals: ['crystal_spikes', 'glow'],
  },
  gas_giant_rings: {
    id: 'gas_giant_rings',
    name: 'Gasriese-Ringe',
    blurb: 'Dichte Ringfelder mit Förderbojen.',
    tags: ['fuel', 'rings'],
    baseYield: { fuel: 3, ore: 1 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 3 },
    hazards: { gravity: 2 },
    build: { allowed: ['refinery', 'tank_yard'] },
    adjacency: { prefers: ['asteroid_belt', 'jetstream'] },
    palette: { base: '#3c2f22', edge: '#2a2017', accent: '#e0b27a' },
    decals: ['rings', 'extractors'],
  },
  jetstream: {
    id: 'jetstream',
    name: 'Sonnenwind-Jetstream',
    blurb: 'Schneller, stabiler Äther-Windkorridor.',
    tags: ['route', 'wind'],
    baseYield: { fuel: 1, influence: 1 },
    moveCost: { airship: 1, frigate: 1, dreadnought: 2 },
    hazards: { radiation: 1 },
    build: { allowed: ['windcatcher', 'signal_bridge'] },
    adjacency: { prefers: ['gas_giant_rings', 'trade_lane'], avoids: ['aether_storm'] },
    palette: { base: '#214050', edge: '#142631', accent: '#76b3c8' },
    decals: ['stream_lines'],
  },
  gravity_shear: {
    id: 'gravity_shear',
    name: 'Schwerkraftbruch',
    blurb: 'Instabile Scherkräfte, Raumzeit-Knarzen.',
    tags: ['anomaly', 'gravity', 'hazard'],
    baseYield: { research: 2 },
    moveCost: { airship: 3, frigate: 4, dreadnought: 5 },
    hazards: { gravity: 3, anomaly: 2 },
    build: { allowed: ['anchor_relay'] },
    adjacency: { prefers: ['relic_vault'], avoids: ['trade_lane', 'brass_metropolis'] },
    palette: { base: '#1c1a2a', edge: '#0f0e17', accent: '#bd93f9' },
    decals: ['warp_ripples'],
  },
  lava_plume: {
    id: 'lava_plume',
    name: 'Lavaplume',
    blurb: 'Geothermische Schwebeinseln und Schlote.',
    tags: ['heat', 'mining'],
    baseYield: { ore: 2, fuel: 1 },
    moveCost: { airship: 2, frigate: 3, dreadnought: 3 },
    hazards: { heat: 3, corrosion: 1 },
    build: { allowed: ['smelter', 'thermal_plant'] },
    adjacency: { prefers: ['soot_cloud', 'asteroid_belt'], avoids: ['ice_field'] },
    palette: { base: '#4a1f16', edge: '#2b100b', accent: '#ff6b3a' },
    decals: ['vents', 'slag'],
  },
  aether_well: {
    id: 'aether_well',
    name: 'Ätherquelle',
    blurb: 'Konzentrierter Ätherbrunnen – selten und mächtig.',
    tags: ['aether', 'unique'],
    baseYield: { aether: 4 },
    moveCost: { airship: 2, frigate: 2, dreadnought: 3 },
    hazards: { anomaly: 2, storm: 1 },
    build: { allowed: ['prime_collector'] },
    adjacency: { prefers: ['aether_nebula', 'crystal_reef'], avoids: ['soot_cloud'] },
    palette: { base: '#432a62', edge: '#2a1b3f', accent: '#ffd166' },
    decals: ['spiral'],
  },
  skyfarms: {
    id: 'skyfarms',
    name: 'Agrar-Plattformen',
    blurb: 'Schwebe-Terrassen mit Kondens-Gewächshäusern.',
    tags: ['food', 'colony'],
    baseYield: { food: 3, luxury: 1 },
    moveCost: { airship: 1, frigate: 2, dreadnought: 2 },
    hazards: { piracy: 1 },
    build: { allowed: ['plantation', 'cold_chain', 'hab_block'] },
    adjacency: { prefers: ['brass_metropolis', 'trade_lane'], avoids: ['aether_storm'] },
    palette: { base: '#33533a', edge: '#243a29', accent: '#9edc8b' },
    decals: ['terraces'],
  },
  ice_field: {
    id: 'ice_field',
    name: 'Eisfeld',
    blurb: 'Kalte Kryo-Nebel und stille Kristalle.',
    tags: ['ice', 'fuel', 'research'],
    baseYield: { fuel: 1, research: 1 },
    moveCost: { airship: 2, frigate: 3, dreadnought: 3 },
    hazards: { corrosion: 1 },
    build: { allowed: ['cryo_lab', 'cooling_spire'] },
    adjacency: { prefers: ['gas_giant_rings', 'aether_nebula'], avoids: ['lava_plume'] },
    palette: { base: '#2b3e4f', edge: '#1b2935', accent: '#bfe8ff' },
    decals: ['ice_crust'],
  },
} satisfies Record<string, HexBiome>;

/** Zugriff als sortierte Liste, z. B. für Dropdowns. */
export const ALL_BIOMES: HexBiome[] = Object.values(BIOMES);
